databases:
  - name: realtime_search
    databaseName: realtime_search
    user: realtime_search
    plan: free

services:
  - type: web
    name: realtime_search
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/rails db:create && ./bin/rails db:migrate && ./bin/rails db:seed && ./bin/rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: realtime_search
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
